import graphviz

dot = graphviz.Digraph(comment='EMAI Preparation')

dot.node('root', 'EMAI Preparation')

dot.node('Academic Track', 'Academic Track')
dot.edge('root', 'Academic Track')

dot.node('Core AI/ML', 'Core AI/ML')
dot.edge('Academic Track', 'Core AI/ML')
dot.node('Online courses', 'Online courses')
dot.edge('Core AI/ML', 'Online courses')
dot.node('University classes', 'University classes')
dot.edge('Core AI/ML', 'University classes')
dot.node('Research projects', 'Research projects')
dot.edge('Core AI/ML', 'Research projects')

dot.node('Mathematics', 'Mathematics')
dot.edge('Academic Track', 'Mathematics')
dot.node('Linear Algebra', 'Linear Algebra')
dot.edge('Mathematics', 'Linear Algebra')
dot.node('Statistics', 'Statistics')
dot.edge('Mathematics', 'Statistics')
dot.node('Probability', 'Probability')
dot.edge('Mathematics', 'Probability')

dot.node('Publications', 'Publications')
dot.edge('Academic Track', 'Publications')
dot.node('Research papers', 'Research papers')
dot.edge('Publications', 'Research papers')
dot.node('Technical blogs', 'Technical blogs')
dot.edge('Publications', 'Technical blogs')

dot.node('Technical Skills', 'Technical Skills')
dot.edge('root', 'Technical Skills')

dot.node('Programming', 'Programming')
dot.edge('Technical Skills', 'Programming')
dot.node('Python', 'Python')
dot.edge('Programming', 'Python')
dot.node('ML Libraries', 'ML Libraries')
dot.edge('Programming', 'ML Libraries')
dot.node('Cloud platforms', 'Cloud platforms')
dot.edge('Programming', 'Cloud platforms')

dot.node('Projects', 'Projects')
dot.edge('Technical Skills', 'Projects')
dot.node('GitHub portfolio', 'GitHub portfolio')
dot.edge('Projects', 'GitHub portfolio')
dot.node('Personal AI projects', 'Personal AI projects')
dot.edge('Projects', 'Personal AI projects')
dot.node('Open source contributions', 'Open source contributions')
dot.edge('Projects', 'Open source contributions')

dot.node('Certifications', 'Certifications')
dot.edge('Technical Skills', 'Certifications')
dot.node('ML/AI certs', 'ML/AI certs')
dot.edge('Certifications', 'ML/AI certs')
dot.node('Cloud certs', 'Cloud certs')
dot.edge('Certifications', 'Cloud certs')

dot.node('Documentation', 'Documentation')
dot.edge('root', 'Documentation')

dot.node('CV/Resume', 'CV/Resume')
dot.edge('Documentation', 'CV/Resume')
dot.node('Projects', 'Projects')
dot.edge('CV/Resume', 'Projects')
dot.node('Skills', 'Skills')
dot.edge('CV/Resume', 'Skills')
dot.node('Achievements', 'Achievements')
dot.edge('CV/Resume', 'Achievements')

dot.node('Motivation Letter', 'Motivation Letter')
dot.edge('Documentation', 'Motivation Letter')
dot.node('Program alignment', 'Program alignment')
dot.edge('Motivation Letter', 'Program alignment')
dot.node('Personal story', 'Personal story')
dot.edge('Motivation Letter', 'Personal story')
dot.node('Future goals', 'Future goals')
dot.edge('Motivation Letter', 'Future goals')

dot.node('Recommendations', 'Recommendations')
dot.edge('Documentation', 'Recommendations')
dot.node('Professors', 'Professors')
dot.edge('Recommendations', 'Professors')
dot.node('Supervisors', 'Supervisors')
dot.edge('Recommendations', 'Supervisors')
dot.node('Industry contacts', 'Industry contacts')
dot.edge('Recommendations', 'Industry contacts')

dot.node('Interview Prep', 'Interview Prep')
dot.edge('root', 'Interview Prep')

dot.node('Technical', 'Technical')
dot.edge('Interview Prep', 'Technical')
dot.node('AI concepts', 'AI concepts')
dot.edge('Technical', 'AI concepts')
dot.node('Project discussions', 'Project discussions')
dot.edge('Technical', 'Project discussions')
dot.node('Problem solving', 'Problem solving')
dot.edge('Technical', 'Problem solving')

dot.node('Behavioral', 'Behavioral')
dot.edge('Interview Prep', 'Behavioral')
dot.node('STAR responses', 'STAR responses')
dot.edge('Behavioral', 'STAR responses')
dot.node('Program knowledge', 'Program knowledge')
dot.edge('Behavioral', 'Program knowledge')
dot.node('Cultural fit', 'Cultural fit')
dot.edge('Behavioral', 'Cultural fit')

dot.node('Research', 'Research')
dot.edge('Interview Prep', 'Research')
dot.node('Faculty research', 'Faculty research')
dot.edge('Research', 'Faculty research')
dot.node('University programs', 'University programs')
dot.edge('Research', 'University programs')
dot.node('Industry trends', 'Industry trends')
dot.edge('Research', 'Industry trends')

dot.render('emai_preparation', format='png', view=True)